SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `musakorner`
--

CREATE TABLE IF NOT EXISTS `playlist` (
`ID` int(10) unsigned NOT NULL,
  `session` int(11) NOT NULL,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `song` (
`ID` int(11) NOT NULL,
  `playlist_ID` int(11) NOT NULL,
  `votes` int(11) NOT NULL DEFAULT '0',
  `has_been_played` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

ALTER TABLE `playlist`
 ADD PRIMARY KEY (`ID`), ADD UNIQUE KEY `session` (`session`);

ALTER TABLE `song`
 ADD PRIMARY KEY (`ID`);

ALTER TABLE `playlist`
MODIFY `ID` int(10) unsigned NOT NULL AUTO_INCREMENT;

ALTER TABLE `song`
MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
